version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arqueo-server-1
    image: arqueo-server
    networks:
      - red-gane-int
    env_file:
      - .env
    environment:
      DB_SERVIRE_USER: "cliente"
      DB_SERVIRE_PASS: "adminadmon"
      DB_SERVIRE_HOST: "172.20.1.92"
      DB_SERVIRE_USE: "Gane"
      DB_SERVIRED_USER: "cliente"
      DB_SERVIRED_PASS: "adminadmon"
      DB_SERVIRED_HOST: "172.20.1.92"
      DB_SERVIRED_USE: "appseguimiento"
      DB_DIALECT_CHAT: "mysql"

  web-metas:
    image: nginx:stable-alpine3.19-slim
    container_name: web_arqueo
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "3757:3757"
    networks:
      - red-gane-int

networks:
  red-gane-int:
    external: true
