version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arqueo-server-servired-1
    image: arqueo-server-servired
    networks:
      - red-gane-int

  web_arqueo_servired:
    image: nginx:stable-alpine3.19-slim
    container_name: web_arqueo_servired
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "3757:3757"
    networks:
      - red-gane-int

networks:
  red-gane-int:
    external: true
