version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arqueo-server-1
    image: arqueo-server
    ports:
      - "3000:3000"

  web-metas:
    image: nginx:stable-alpine3.19-slim
    container_name: web_arqueo
    volumes:
      - ./client/dist:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
