import { Request, Response } from 'express';
import { arqueo, initChatBoxModel } from '../models/arqueo.model';

export const getArqueo = async (req: Request, res: Response): Promise<void> => {
    const data = req.params;
    const { zona } = data;
    const { page = '1', limit = '50' } = req.query; // Obtener los parámetros de paginación

    if (zona === undefined) {
        res.status(400).json('Zona no válida');
        return;
    }

    const empresa = zona === 'Multired' ? 'Multired' : 'Servired';
    initChatBoxModel(empresa);

    try {
        const offset = (parseInt(page as string, 10) - 1) * parseInt(limit as string, 10);
        const Chat = await arqueo.findAll({
            attributes: [
                'supervisor',
                'id',
                'ip',
                'nombres',
                'documento',
                'sucursal',
                'puntodeventa',
                'ventabruta',
                'baseefectivo',
                'cartera',
                'totalingreso',
                'chancesabonados',
                'chancespreimpresos',
                'premiospagados',
                'efectivocajafuerte',
                'tirillarecaudo',
                'totalegresos',
                'totalbilletes',
                'totalmonedas',
                'totalarqueo',
                'sobrantefaltante',
                'canti_billete_cienmil',
                'canti_billete_cincuentamil',
                'canti_billete_veintemil',
                'canti_billete_diezmil',
                'canti_billete_cincomil',
                'canti_billete_dosmil',
                'canti_billete_mil',
                'total_billete_cienmil',
                'total_billete_cincuentamil',
                'total_billete_veintemil',
                'total_billete_diezmil',
                'total_billete_cincomil',
                'total_billete_dosmil',
                'total_billete_mil',
                'canti_moneda_mil',
                'canti_moneda_quinientos',
                'canti_moneda_docientos',
                'canti_moneda_cien',
                'canti_moneda_cincuenta',
                'total_moneda_mil',
                'total_moneda_quinientos',
                'total_moneda_docientos',
                'total_moneda_cien',
                'total_moneda_ciencuenta',
                'total_efectivo',
                'canti_billete_cienmil1',
                'canti_billete_cincuentamil1',
                'canti_billete_veintemil1',
                'canti_billete_diezmil1',
                'canti_billete_cincomil1',
                'canti_billete_dosmil1',
                'canti_billete_mil1',
                'total_billete_cienmil1',
                'total_billete_cincuentamil1',
                'total_billete_veintemil1',
                'total_billete_diezmil1',
                'total_billete_cincomil1',
                'total_billete_dosmil1',
                'total_billete_mil1',
                'canti_moneda_mil1',
                'canti_moneda_quinientos1',
                'canti_moneda_docientos1',
                'canti_moneda_cien1',
                'canti_moneda_cincuenta1',
                'total_moneda_mil1',
                'total_moneda_quinientos1',
                'total_moneda_docientos1',
                'total_moneda_cien1',
                'total_moneda_ciencuenta1',
                'total_efectivo1',
                'total_premios_pagados1',
                'total',
                'total_premios_pagados',
                'base_efectivos',
                'tirilla_recaudos',
                'entrega_colocador',
                'sobrantefaltante_caja',
                'colocador_cajafuerte',
                'rollos_bnet',
                'rollos_fisicos',
                'diferencia',
                'nombre_juego',
                'cantidad_bnet',
                'cantidad_fisicos',
                'cantidad_faltante',
                'cantidad_tiquete',
                'descargado',
                'nombre_juego2',
                'cantidad_bnet2',
                'cantidad_fisicos2',
                'cantidad_faltante2',
                'cantidad_tiquete2',
                'descargado2',
                'nombre_juego3',
                'cantidad_bnet3',
                'cantidad_fisicos3',
                'cantidad_faltante3',
                'cantidad_tiquete3',
                'descargado3',
                'nombre_juego4',
                'cantidad_bnet4',
                'cantidad_fisicos4',
                'cantidad_faltante4',
                'cantidad_tiquete4',
                'descargado4',
                'totaldescargados',
                'totalvalor',
                'requisito1',
                'observacion1',
                'requisito2',
                'observacion2',
                'requisito3',
                'observacion3',
                'requisito4',
                'observacion4',
                'requisito5',
                'observacion5',
                'requisito6',
                'observacion6',
                'requisito7',
                'observacion7',
                'requisito8',
                'observacion8',
                'requisito9',
                'observacion9',
                'requisito10',
                'observacion10',
                'requisito11',
                'observacion11',
                'requisito12',
                'observacion12',
                'requisito13',
                'observacion13',
                'requisito14',
                'observacion14',
                'requisito15',
                'observacion15',
                'requisito16',
                'observacion16',
                'requisito17',
                'observacion17',
                'requisito18',
                'observacion18',
                'requisito19',
                'observacion19',
                'requisito20',
                'observacion20',
                'requisito21',
                'observacion21',
                'requisito22',
                'observacion22',
                'requisito23',
                'observacion23',
                'requisito24',
                'observacion24',
                'requisito25',
                'observacion25',
                'requisito26',
                'observacion26',
                'requisito27',
                'observacion27',
                'requisito28',
                'observacion28',
                'requisito29',
                'requisito30',
                'imagen_observacion',
                'nombre_observacion',
                'firma_auditoria',
                'firma_colocadora',
                'fechavisita',
                'horavisita',
                'latitud',
                'longitud'
            ],
            offset: offset,
            limit: parseInt(limit as string, 10),
            order: [['fechavisita', 'DESC']],
        });
        res.status(200).json(Chat);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Internal Server Error' });
    }
};

export const getArqueos = async (req: Request, res: Response): Promise<void> => {
    const data = req.params;
    const { zona, id } = data;

    if (zona === undefined) {
        res.status(400).json('Zona no válida');
        return;
    }

    const empresa = zona === 'Multired' ? 'Multired' : 'Servired';
    initChatBoxModel(empresa);

    try {
        const Chat = await arqueo.findAll({
            attributes: [
                'supervisor',
                'id',
                'ip',
                'nombres',
                'documento',
                'sucursal',
                'puntodeventa',
                'ventabruta',
                'baseefectivo',
                'cartera',
                'totalingreso',
                'chancesabonados',
                'chancespreimpresos',
                'premiospagados',
                'efectivocajafuerte',
                'tirillarecaudo',
                'totalegresos',
                'totalbilletes',
                'totalmonedas',
                'totalarqueo',
                'sobrantefaltante',
                'canti_billete_cienmil',
                'canti_billete_cincuentamil',
                'canti_billete_veintemil',
                'canti_billete_diezmil',
                'canti_billete_cincomil',
                'canti_billete_dosmil',
                'canti_billete_mil',
                'total_billete_cienmil',
                'total_billete_cincuentamil',
                'total_billete_veintemil',
                'total_billete_diezmil',
                'total_billete_cincomil',
                'total_billete_dosmil',
                'total_billete_mil',
                'canti_moneda_mil',
                'canti_moneda_quinientos',
                'canti_moneda_docientos',
                'canti_moneda_cien',
                'canti_moneda_cincuenta',
                'total_moneda_mil',
                'total_moneda_quinientos',
                'total_moneda_docientos',
                'total_moneda_cien',
                'total_moneda_ciencuenta',
                'total_efectivo',
                'canti_billete_cienmil1',
                'canti_billete_cincuentamil1',
                'canti_billete_veintemil1',
                'canti_billete_diezmil1',
                'canti_billete_cincomil1',
                'canti_billete_dosmil1',
                'canti_billete_mil1',
                'total_billete_cienmil1',
                'total_billete_cincuentamil1',
                'total_billete_veintemil1',
                'total_billete_diezmil1',
                'total_billete_cincomil1',
                'total_billete_dosmil1',
                'total_billete_mil1',
                'canti_moneda_mil1',
                'canti_moneda_quinientos1',
                'canti_moneda_docientos1',
                'canti_moneda_cien1',
                'canti_moneda_cincuenta1',
                'total_moneda_mil1',
                'total_moneda_quinientos1',
                'total_moneda_docientos1',
                'total_moneda_cien1',
                'total_moneda_ciencuenta1',
                'total_efectivo1',
                'total_premios_pagados1',
                'total',
                'total_premios_pagados',
                'base_efectivos',
                'tirilla_recaudos',
                'entrega_colocador',
                'sobrantefaltante_caja',
                'colocador_cajafuerte',
                'rollos_bnet',
                'rollos_fisicos',
                'diferencia',
                'nombre_juego',
                'cantidad_bnet',
                'cantidad_fisicos',
                'cantidad_faltante',
                'cantidad_tiquete',
                'descargado',
                'nombre_juego2',
                'cantidad_bnet2',
                'cantidad_fisicos2',
                'cantidad_faltante2',
                'cantidad_tiquete2',
                'descargado2',
                'nombre_juego3',
                'cantidad_bnet3',
                'cantidad_fisicos3',
                'cantidad_faltante3',
                'cantidad_tiquete3',
                'descargado3',
                'nombre_juego4',
                'cantidad_bnet4',
                'cantidad_fisicos4',
                'cantidad_faltante4',
                'cantidad_tiquete4',
                'descargado4',
                'totaldescargados',
                'totalvalor',
                'requisito1',
                'observacion1',
                'requisito2',
                'observacion2',
                'requisito3',
                'observacion3',
                'requisito4',
                'observacion4',
                'requisito5',
                'observacion5',
                'requisito6',
                'observacion6',
                'requisito7',
                'observacion7',
                'requisito8',
                'observacion8',
                'requisito9',
                'observacion9',
                'requisito10',
                'observacion10',
                'requisito11',
                'observacion11',
                'requisito12',
                'observacion12',
                'requisito13',
                'observacion13',
                'requisito14',
                'observacion14',
                'requisito15',
                'observacion15',
                'requisito16',
                'observacion16',
                'requisito17',
                'observacion17',
                'requisito18',
                'observacion18',
                'requisito19',
                'observacion19',
                'requisito20',
                'observacion20',
                'requisito21',
                'observacion21',
                'requisito22',
                'observacion22',
                'requisito23',
                'observacion23',
                'requisito24',
                'observacion24',
                'requisito25',
                'observacion25',
                'requisito26',
                'observacion26',
                'requisito27',
                'observacion27',
                'requisito28',
                'observacion28',
                'requisito29',
                'requisito30',
                'imagen_observacion',
                'nombre_observacion',
                'firma_auditoria',
                'firma_colocadora',
                'fechavisita',
                'horavisita',
                'latitud',
                'longitud'
            ],
            where: {
                id: id
            },
            order: [['fechavisita', 'DESC']],
        });
        res.status(200).json(Chat);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Internal Server Error' });
    }
};